services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FLASK_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 3